### ISSUE TITLE
CUDA OOM on NeuralMemory

### ISSUE THREAD

**Issue by ddidacus** [lucidrains/titans-pytorch#33]
Hello,
I am trying to embed the NeuralMemory module in transformers implementation of llama. 
The model being considered is llama 3.2 1B.
I modified the decoder layer as follows:
```
class TitanLlamaDecoderLayer(nn.Module):
    def __init__(self, config: LlamaConfig, layer_idx: int, gated:bool = False):
        super().__init__()
        self.gated = gated
        self.hidden_size = config.hidden_size
        if hasattr(config, "chunk_size"): self.chunk_size = config.chunk_size
        else: self.chunk_size = 128

        config.sliding_window = True # main difference wrt. llama
        self.self_attn = MistralAttention(config=config, layer_idx=layer_idx)

        self.memory = NeuralMemory(
            dim = config.hidden_size,
            chunk_size = self.chunk_size # set to smaller chunk size for better perf on smaller sequence lengths (but more memory usage)
        )
        self.memory_state = None
        self.mlp = LlamaMLP(config)
        self.input_layernorm = LlamaRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = LlamaRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[Tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.FloatTensor, Optional[Tuple[torch.FloatTensor, torch.FloatTensor]]]:
      
        # Memory As Layer (MAL)
        if not self.gated:
            residual = hidden_states
            hidden_states, self.memory_state = self.memory(seq=hidden_states, state=self.memory_state)
            hidden_states = residual + hidden_states

        # Layer norm
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        
        # Memory As Gate (MAG)
        if self.gated: 
            hidden_states, self.memory_state = self.memory(seq=hidden_states, state=self.memory_state)
            attn_out_gates = hidden_states.sigmoid()
            hidden_states *= attn_out_gates

        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states

        outputs = (hidden_states,)
        if output_attentions:
            outputs += (self_attn_weights,)

        return outputs
```
and after replacing the llama layers I tried to do a forward pass. It works with short sequences, but when trying to feed e.g. 6500 tokens, I get the CUDA OOM as follows:
```
Traceback (most recent call last):
  File "/network/scratch/d/user/titans/llama-titans/test_local.py", line 22, in <module>
    output = model.generate(toks, **generation_kwargs)
  File "/path_to/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/transformers/generation/utils.py", line 2255, in generate
    result = self._sample(
  File "/path_to/lib/python3.10/site-packages/transformers/generation/utils.py", line 3254, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 834, in forward
    outputs = self.model(
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 592, in forward
    layer_outputs = decoder_layer(
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/network/scratch/d/user/titans/llama-titans/llama_titans/llama.py", line 80, in forward
    hidden_states, self.memory_state = self.memory(seq=hidden_states, state=self.memory_state)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/network/scratch/d/user/titans/llama-titans/llama_titans/neural_memory.py", line 940, in forward
    next_updates, next_neural_mem_state = self.store_memories(
  File "/network/scratch/d/user/titans/llama-titans/llama_titans/neural_memory.py", line 734, in store_memories
    update = self.assoc_scan(1. - decay_factor, update, prev = last_update, remove_prev = False)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/path_to/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/network/scratch/d/user/titans/titans-pytorch/titans_pytorch/associative_scan.py", line 144, in forward
    _, out = associative_scan(binary_operator, (gates, inputs))
  File "/network/scratch/d/user/titans/titans-pytorch/titans_pytorch/associative_scan.py", line 100, in associative_scan
    return _scan(elems)
  File "/network/scratch/d/user/titans/titans-pytorch/titans_pytorch/associative_scan.py", line 98, in _scan
    return list(map(_interleave, even_elems, odd_elems))
  File "/network/scratch/d/user/titans/titans-pytorch/titans_pytorch/associative_scan.py", line 109, in _interleave
    stacked = torch.stack([a, b], dim=2)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.25 GiB. GPU 0 has a total capacity of 79.44 GiB of which 1.92 GiB is free. Including non-PyTorch memory, this process has 77.51 GiB memory in use. Of the allocated memory 76.74 GiB is allocated by PyTorch, and 279.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

It seems weird to me because if I understood correctly, the NeuralMemory model splits into chunks the input sequence while processing it. Any feedback on the implementation is much appreciated. Thank you.

**Comment by ddidacus** [comment]
fixed by increasing `chunk_size=2048` and making sure that the `attn_interface` is `flash_attention_x`. Otherwise `sliding_window` will be ignored and memory will blow up.
